vim.keymap.set("n", "-", MiniFiles.open)
vim.keymap.set("n", "<leader>do", MiniDiff.toggle_overlay)
vim.keymap.set("n", "<leader>mm", MiniMap.toggle)
vim.keymap.set("n", "<leader>ds", vim.diagnostic.open_float)
vim.keymap.set("n", "<leader>lf", vim.lsp.buf.format)
vim.keymap.set("n", "<leader>f", "<CMD>Pick files<CR>")
vim.keymap.set("n", "<leader>h", "<CMD>Pick help<CR>")
vim.keymap.set("n", "<leader>g", "<CMD>Pick grep_live<CR>")
vim.keymap.set("n", "<leader>pi", "<CMD>PasteImage<CR>")
vim.keymap.set("n", "<leader>o", "<CMD>Outline<CR>")

local flash = require("flash")
vim.keymap.set({ "n", "x", "o" }, "<leader>s", flash.jump, { desc = "Flash Jump" })
