source = ./conf/00-env.conf
source = ./conf/00-variables.conf
source = ./conf/10-dwindle.conf
source = ./conf/10-input.conf
source = ./conf/10-keybindings.conf
source = ./conf/10-monitors.conf
source = ./conf/80-startup-applications.conf
source = ./conf/99-animations.conf
source = ./conf/99-look-and-feel.conf
source = ./conf/99-misc.conf
source = ./conf/99-window-rules.conf
