# --- Monitor configuration for Hyprland
#
# See https://wiki.hyprland.org/Configuring/Monitors/

monitor=,preferred,auto,auto

# Trigger when the lid is closed
bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"

# Trigger when the lid is opened
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, preferred, auto, auto"

# Automatically toggle internal display based on external monitor presence
# exec-on-monitor-add=~/.config/hypr/scripts/disable-edp-on-external.sh
# exec-on-monitor-remove=~/.config/hypr/scripts/disable-edp-on-external.sh
