# --- Start-up applications for Hyprland
#
# See https://wiki.hypr.land/Configuring/Keywords/#executing.

exec-once = uwsm app -- ashell
exec-once = uwsm app -- awww-daemon
exec-once = systemctl --user start hyprpolkitagent
