# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule {
  name = "Fix some dragging issues with XWayland"

  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false

  no_focus = true
}


windowrule {
  name = "Ignore maximize requests from apps. You'll probably like this."

  match:class = .*

  suppress_event = maximize
}
